baseURL = "https://<your-github-username>.github.io/AnythingAboutITBlog/"
title = "Anything About IT"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
defaultContentLanguage = "en"
hasCJKLanguage = true

[services]
  [services.disqus]
    shortname = ""
  [services.googleAnalytics]
    id = ""

[pagination]
  pagerSize = 6

[outputs]
home = ["HTML", "RSS"]

[permalinks]
  post = "/:year/:month/:slug/"

[params]
  header_image = "img/anythingaboutit_hero.png"
  SEOTitle = "Anything About IT"
  description = "by Alex Verboon"
  keyword = "security,microsoft,defender XDR, Sentinel, PowerShell, KQL"
  slogan = "Learning, Building, Sharing"
  upstreamAttribution = false

  image_404 = "img/404.png"
  title_404 = "Page not found"
  omit_categories = false

  page_view_counter = false
  leancloud_app_id = ""
  leancloud_app_key = ""

  algolia_search = false
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  sidebar_about_description = "Anything About IT"
  sidebar_avatar = "img/avatar.png"

  featured_tags = true
  featured_condition_size = 1

  bookmarks = false
  about_me = true

  last_posts = true

  [params.social]
  rss = true
  email = ""
  github = "https://github.com/alexverboon"
  linkedin = "https://www.linkedin.com/in/verboonalex/"
  twitter = "https://x.com/alexverboon"
  microsoft_mvp = "https://mvp.microsoft.com/en-US/mvp/profile/9d58ee5f-ed9f-ea11-a811-000d3a8ccaf5"
  stackoverflow = ""

  [[params.additional_menus]]
  title = "ARCHIVE"
  href = "/archive/"

    [[params.additional_menus]]
  title = "ABOUT"
  href = "/about/"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"]

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 2
  [markup.highlight]
    style = "dracula"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[mediaTypes]
  [mediaTypes.'font/woff']
    suffixes = ['woff']
  [mediaTypes.'font/woff2']
    suffixes = ['woff2']
